default_preferences:
  list-file-name: urls.txt
  path: ./Youtube_Downloads
  resolution: 720
  session: url
  video: audio
user_preferences:
  list-file-name: urls.txt
  path: ./Youtube_Downloads
  resolution: 720
  session: search
  video: audio
